import clsx from "clsx";
import "./globals.css";
import { Dancing_Script, Poppins } from "next/font/google";

const dancingScript = Dancing_Script({
  subsets: ["latin"],
  variable: "--dancing-script",
});
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={clsx(
          `${dancingScript.variable} ${poppins.variable} overflow-hidden scroll-smooth font-sans`,
          {
            "debug-screens": process.env.NODE_ENV !== "production",
          }
        )}
      >
        {children}
      </body>
    </html>
  );
}
