name: Deploy

on:
  push:
    branches: [rizman]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/shaqi.wedding.farhandev.cloud
            git pull origin rizman
            docker-compose down
            docker-compose up --build -d
